FROM ubuntu
MAINTAINER Nathaniel Talbott <nathaniel@spreedly.com>

RUN echo "debconf debconf/frontend select Teletype" | debconf-set-selections

RUN apt-get update

# Install packages
RUN apt-get install -y \
#   for downloading Riak
    wget

# Download and install Riak
RUN wget -nv <%= ENV["DOWNLOAD_URL"] %>
RUN dpkg -i <%= ENV["DOWNLOAD_URL"].split("/").last %>

# Put our custom Riak config in place
ADD app.config /etc/riak/app.config
RUN echo "ulimit -n 4096" >> /etc/default/riak
RUN mkdir -p /tmp/riak

# Expose Riak HTTP & Protocol Buffers
EXPOSE 8087 8098

CMD ["/usr/sbin/riak", "console"]
